name: flutter_hb_salesforce
description: A Flutter project for Salesforce integration.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  rxdart: ^0.28.0
  intl: ^0.20.2
  flutter_layout_grid: ^2.0.8
  sembast: ^3.8.5+2
  sembast_web: ^2.4.2
  path_provider: ^2.1.5
  mocktail: ^1.0.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    # Add all product images
    - assets/products/

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/hb-logo.png"
  image_path_android: "assets/hb-logo.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/hb-logo-transparent.png"
  macos:
    generate: true
    image_path: "assets/hb-logo-transparent.png"
  web:
    generate: true
    image_path: "assets/hb-logo-transparent.png"
