name: Run Tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/63122434/436422
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter test